databases:
  - name: underground-cafe-db
    plan: free
    databaseName: underground_cafe
    user: underground_cafe

services:
  - type: web
    name: underground-cafe
    runtime: docker
    plan: free
    healthCheckPath: /up
    preDeployCommand: php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: underground-cafe-db
          property: connectionString
      - key: DB_URL
        fromDatabase:
          name: underground-cafe-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_NAME
        value: Underground Cafe
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: MIDTRANS_SERVER_KEY
        value: SB-Mid-server-t8MFom-L-ZMiJYA0lPvUX8hc
      - key: MIDTRANS_CLIENT_KEY
        value: SB-Mid-client-07PMj5xBlweORohB
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
